version: '3.8'
services:
  backend:
    build: ./back
    command: uvicorn app.main:app --root-path /api --proxy-headers --host 0.0.0.0 --port 8000
    restart: always
    ports:
      - "3001:8000"
    expose:
      - 8000

  frontend:
    build: ./front
    restart: always
    ports:
      - "3000:3000"
    expose:
      - 3000

  postgres:
    container_name: postgres
    image: postgres:latest
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB} #optional (specify default database instead of $POSTGRES_DB)
    ports:
      - "5432:5432"
    restart: always
