version: '3.8'
services:
  backend:
    build: ./back
    command: uvicorn app.main:app --root-path /api --proxy-headers --host 0.0.0.0 --port 8000
    restart: always
    ports:
      - "8000:8000"
    expose:
      - 8000

  frontend:
    build: ./front
    restart: always
    ports:
      - "3000:3000"
    expose:
      - 3000